services:
  postgres:
    image: postgres:16
    container_name: gym-manager-db
    environment:
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym1234
      POSTGRES_DB: gym_manager
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
